### ISSUE TITLE
Web Design: Superlatives

### ISSUE THREAD

**Issue by B14S1lv4** [Emyrk/stravacollector#20]
Superlatives: name, description (including personal descriptors), and icon design

Superlatives? (Check for summit problems)
- Earliest activity start == “Early Bird”
- Latest end time = night owl
- Most stoppage == “Most relaxed”
- Least stoppage == extreme cyclist
- Max watts = watt machine
- Shortest ride = most efficient
- Longest ride = 
- Most elevation = mountain climber
- Max amount of PRs = most improved 
- Highest average cadence = super spinner
- Lowest average cadence = grind it out
- Suffer score = most pain
- Best of $Segment

**Comment by Emyrk** [comment]
48x48 circle image

**Comment by B14S1lv4** [comment]
Early Bird: [name] gets the worm with their x start time. 

Night Owl: Aren’t you glad you didn’t wait up with their x end time?

Coffee Break: Stopped and smelled the roses with x minutes of stoppage. 

Dory: Just keep swimming. Only x minutes of stoppage.

The Edison: Powering Austin with x average watts.

Roadrunner: Legs a’blur with average cadence of x rpm.

Mortar & Pestle: Grinding so hard with average cadence of x rpm. 

Masochist: Definitely type 2 fun with this x suffer score.

Overachiever: Thinking they’re so cool with x achievements. 

Wanderer: Must’ve gotten lost taking x miles to finish. 

MVP: Most Vigilant Path-Follower took no detours with only x miles to finish. 

Yawner: Not working hard with a x bpm average heart rate. 

Winner: Didn’t actually win but built this site so they get a participation trophy.

**Comment by B14S1lv4** [comment]
@Emyrk icons are ready: https://drive.google.com/drive/folders/1Q8UdoXj3kSShxCArrrL3RUt0rwfaD3UD?usp=drive_link

**Comment by B14S1lv4** [comment]
Additions:
- Turtle: Taking their sweet time with an average of x mph.
- Hare: Must’ve wanted the ride to be over with an average of x mph.

Icons have been added to the drive

**Comment by B14S1lv4** [comment]
Cardiac Arrest: Anyone have a defib? Gonna need it with this x bpm average heart rate.
